language: php

php:
  - 5.4
  - 5.5

before_script:
 - composer self-update
 - composer install --prefer-source --dev
  
script:
  - mkdir -p build/logs
  - cd tests
  - phpunit
  - cd ../

after_script:
  - php vendor/bin/coveralls -v
